//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppAutresApprochesEF.Model5EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaysFilm
    {
        public int id { get; set; }
        public Nullable<int> idFilm { get; set; }
        public Nullable<int> idPays { get; set; }
        public string mois { get; set; }
    
        public virtual Films Films { get; set; }
        public virtual pays pays { get; set; }
    }
}
