//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppAutresApprochesEF.Model
{
    using System;
    
    public partial class Adresse
    {
        public int Numero { get; set; }
        public string Rue { get; set; }
        public string CP { get; set; }
        public string Complement { get; set; }
    }
}
